language: node_js
node_js: '11.8.0'
os: linux
git: 
  lfs_skip_smudge: true
notifications:
  slack:
    secure: n6FkfVu3nv+uYdRr+PO+V+/rIugahJsH2z0UNLM7F2DrgJAfJg8mc4c/FWzJWrKHzkGwy6yAKqyKfjIjIn2c0ud0pILus9ct386ul97L3BILCb1uyJSBbrkQi0f+ZAHs4JCb4Syx00a/U9k2+OGKWZhmy5bx/3Z0tsOiDttqhdepyNufQJPrOu9konIcl0AoHbXVNYkmKyCa5NS39dlq3zScUL/80q4JNL+b4noVIKOGl/L7VpGu+OLxCqfdKhWccPeb1yqtly7j2THiCif6/nnbBJSG2sXhvdeOYQnQCxQC6XAkquks6b8nmC/q4fxJohDr6DSrmlni4gQTFjD7T4YzSRGeO81aBHZICv9rmIcEgl2h472r5KWzFm8xwaW2lVpzfdY6cqCgklu1c2CWk6hGJR7f1gifEYDqSPXRWSlqXQ2XIhZm2V4Cca9MC0t2qbDVvWIZoN1IunC2uhoFiSdL60zZzQTQygCfK9HKgS7z99V3R5NfTjH9AzeWGDriREbMolsxcQW0vnn6CQAnp5CCQDiKENvil/cFT3o/6FJ+hGAE4uT7D+6jjPyniJYRDlRuLEGEOR8/bADukLQKAVFIwq7T93g5FsjMjOydtc74SpG9WAS97qVATMv9FuTwGK2kJZbNkbK1QjcD8wQvfNLGWi7FSJnRJZTkso29jeU=
  on_success: change
  on_failure: always
tags: true
branches:
  only: 
    - master
    - /^v[0-9]+\.[0-9]+\.[0-9]+/
cache: npm
before_script: npm install
# TODO: uncomment when cloud is available
# before_deploy:
# deploy:
#   skip_cleanup: true
#   provider: script
#   script: bash scripts/deploy.sh
#   on:
#     tags: true
